// src/components/app/avatar.tsx
import { initialsFor } from "@/lib/utils/initials"

const boxes = {
  sm: "h-6 w-6 text-[10px]",
  md: "h-8 w-8 text-xs",
  lg: "h-12 w-12 text-sm",
  xl: "h-16 w-16 text-lg",
} as const

interface AvatarProps {
  /** The name the initials come from — full_name_display, or the username. */
  name?: string | null
  /** Taiga's uploaded picture, when the person has one. */
  photo?: string | null
  /** Background for the initials. Taiga gives every user a colour. */
  color?: string | null
  size?: keyof typeof boxes
  className?: string
}

export function Avatar({ name, photo, color, size = "md", className = "" }: AvatarProps) {
  const label = name ?? ""
  if (photo) {
    return (
      <img
        src={photo}
        alt={label}
        title={label}
        className={`rounded-full object-cover ${boxes[size]} ${className}`}
      />
    )
  }
  return (
    <div
      title={label}
      className={`flex shrink-0 items-center justify-center rounded-full font-medium ${boxes[size]} ${className}`}
      style={color ? { backgroundColor: color } : undefined}
    >
      {initialsFor(name)}
    </div>
  )
}

// src/lib/components/Avatar.svelte
<script lang="ts">
	import { initialsFor } from '$lib/utils/initials';

	/** The name the initials come from — full_name_display, or the username. */
	export let name: string | null | undefined = null;
	/** Taiga's uploaded picture, when the person has one. */
	export let photo: string | null | undefined = null;
	/** Background for the initials. Taiga gives every user a colour. */
	export let color: string | null | undefined = null;
	export let size: 'sm' | 'md' | 'lg' | 'xl' = 'md';
	/** Extra classes, so each place keeps the look it already had. */
	let extraClass = '';
	export { extraClass as class };

	const boxes = {
		sm: 'w-6 h-6 text-[10px]',
		md: 'w-8 h-8 text-xs',
		lg: 'w-12 h-12 text-sm',
		xl: 'w-16 h-16 text-lg'
	};

	$: label = name ?? '';
	$: initials = initialsFor(name);
	$: box = boxes[size];
</script>

{#if photo}
	<img
		src={photo}
		alt={label}
		title={label}
		class="{box} {extraClass} rounded-full object-cover shrink-0"
	/>
{:else}
	<div
		class="{box} {extraClass} rounded-full flex items-center justify-center font-medium shrink-0"
		style={color ? `background-color: ${color}` : ''}
		title={label}
	>
		{initials}
	</div>
{/if}
